---
-  name: User and Group creation
   hosts: linux
   vars:
     users: ["name1","name2"]
   tasks:
     - name: create user list in jinja2 template
       ansible.builtin.template:
         src: user_list.j2
         dest: user_list.html
     - name: show templating results
       set_fact:
         userlist: "{{ lookup('template', './user_list.j2') }}"
     - debug:
         msg: "{{ userlist }}"
     - name: Print user list
       debug:
         msg: "{{ item | replace('\n','')}}"
       with_items: "{{userlist.split('\t')}}"
     - name: Add the user with a specific uid and a primary group of 'ansible-training'
       ansible.builtin.user:
         name: "{{ item | replace('\n','')}}"
         group: ansible-training
       when: item != ""
       with_items: "{{userlist.split('\t')}}"
